terapiketok/routes/boardpanel.py
import datetime, uuid
from flask import Blueprint, render_template_string, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, LoginManager, login_required, logout_user,current_user
from flask_bcrypt import Bcrypt
from ..models import Adminuser, Default_batch, Opening_message, Workingdays, Batches, Booking_tickets
from ..forms import RegisterForm, LoginAdminForm, DefaultBatchForm2, OpeningMessageForm, NewBatchForm, MultipleBatchesForm, NewDateForm, ChangeStatusForm, AddCustomerManualForm, CloseTicketButton, DeleteBatchesForm, MultipleDeleteForm, ConfirmDeleteForm
from ..services.data_processing import format_date_str, format_default_batch_time, get_queue_number
from terapiketok import app, bcrypt, db

from ..services.database import add_default_batch, update_default_batch, update_default_batch2, update_opening_message, add_new_batch, update_batch_status_by_batch, update_batch_status_by_date, add_customer_manually, fetct_queue_number, fetch_available_date_to_edit, update_and_add_new_batch, fetch_max_shifts, delete_batch_by_date_scheduleid, delete_batch_by_id
from ..services.database_renew import DatabaseProcess

boardpanel_bp = Blueprint('boardpanel', __name__, template_folder="../templates/boardpanel")

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "boardpanel.adminlogin_page"
login_manager.login_message_category = "info"

@login_manager.user_loader
def load_user(user_id):
    return Adminuser.query.get(int(user_id))

@boardpanel_bp.before_request
def before_request():
    if current_user.is_authenticated:
        session.permanent = True  # Ensure session cookie is permanent
        db.session.refresh(current_user)  # Refresh user object from database
        session['user_id'] = current_user.user_id  # Update session data

@boardpanel_bp.route('/adminregister', methods=['GET', 'POST'])
def adminregister_page():
    text_header = "register"
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        confirm_password = form.confirm_password.data
        if password == confirm_password:
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            new_user = Adminuser(username=username, hashed_password=hashed_password)
            try:
                db.session.add(new_user)
                db.session.commit()
                flash("Registration successful!", category="success")
                return redirect(url_for("boardpanel.adminlogin_page"))
            except Exception as e:
                flash("Registration failed", category="danger")
        else:
            flash("password not match", category="danger")
    
    print(form.errors)

    return render_template('adminregister.html', text_header=text_header, form=form)

@boardpanel_bp.route('/adminlogin', methods=['GET', 'POST'])
def adminlogin_page():
    text_header = "login"
    form = LoginAdminForm()
    
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = Adminuser.query.filter_by(username=username).first()
        if user:
            if bcrypt.check_password_hash(user.hashed_password, password):
                
                login_user(user)
                return redirect(url_for('boardpanel.boardpanel_page'))

    return render_template('adminlogin.html', text_header=text_header, form=form)

@boardpanel_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout_page():
    logout_user()
    session.clear() # clear all session
    return redirect(url_for("boardpanel.adminlogin_page"))

@boardpanel_bp.route('/boardpanel', methods=['GET', 'POST'])
@login_required
def boardpanel_page():
    today = datetime.date.today()
    text_header = 'Dashboard'
    
    batches = Batches.query.filter(Batches.batch_date >= today).order_by(Batches.batch_date.asc(), Batches.schedule_id.asc()).all()

    return render_template('boardpanel.html', text_header=text_header, batches=batches)

@boardpanel_bp.route('/batches')
def batch_page():
    text_header = "Available Batches"
    return render_template('batches.html', text_header=text_header)

@boardpanel_bp.route('/newdate', methods=['GET', 'POST'])
@login_required
def newdate_page():
    form = NewDateForm()

    if form.validate_on_submit():
        session["target_batch_num"] = form.batches.data
        session["target_batch_date"] = form.batch_date.data
        return redirect(url_for('boardpanel.newbatch_page'))

    default_set = Default_batch.query.filter_by(default_batch_id=1).first()
    batches = default_set.number_of_batches
    new_date = datetime.date.today() + datetime.timedelta(days=1)
    
    return render_template('newdate.html', form=form, batches=batches, new_date=new_date)

@boardpanel_bp.route('/newbatch', methods=['GET', 'POST'])
@login_required
def newbatch_page():
    form = MultipleBatchesForm()

    target_batch_num = session.get("target_batch_num")
    target_batch_date_str = session.get("target_batch_date")
    if target_batch_date_str:
        # print(type(target_batch_date_str))
        formatted_date = format_date_str(target_batch_date_str)
        
    default_set = Default_batch.query.filter_by(default_batch_id=1).first()

    if form.validate_on_submit():
        def get_day_id(date_str):
            day_num = datetime.datetime.strptime(date_str, "%a, %d %b %Y %H:%M:%S %Z").weekday()
            day_data = Workingdays.query.filter_by(day_num=day_num).first()
            return day_data.day_id

        for index, batch_form in enumerate(form.batches):
            schedule_id = index+1
            batch_date = formatted_date
            start_time = batch_form.start_time.data
            end_time = batch_form.end_time.data
            max_tickets = batch_form.capacity.data
            day_id = get_day_id(target_batch_date_str)

            count = add_new_batch(day_id, schedule_id, batch_date, start_time, end_time, max_tickets)
            if count > 0:
                flash(f"Add New Date on {formatted_date}", category="success")    
            else:
                flash("Failed to updated", category="warning")

        return redirect(url_for('boardpanel.boardpanel_page'))
    
    for num in range(target_batch_num):
        cur_batch_attr_start =f"batch{num+1}_start"
        cur_batch_attr_end =f"batch{num+1}_end"
        start_time = getattr(default_set, cur_batch_attr_start)
        end_time = getattr(default_set, cur_batch_attr_end)
        
        batch_form = NewBatchForm(
            start_time = start_time,
            end_time = end_time,
            capacity = default_set.capacity
        )
        form.batches.append_entry(batch_form.data)
    
    return render_template('newbatch.html', form=form, batches=target_batch_num, new_date=formatted_date, default_set=default_set, enumerate=enumerate)

@boardpanel_bp.route('/editoption/<action>', methods=['GET', 'POST'])
@login_required
def editoption_page(action):
    next_action = "delete"
    if action == "delete":
        next_action = "edit"
    today = datetime.date.today()
    start_date = datetime.date(year=2024, month=1, day=1)
    dates_to_edit = fetch_available_date_to_edit(start_date)

    return render_template('editoption.html', head_text=action, next_action=next_action, dates=dates_to_edit)

@boardpanel_bp.route('/edit', methods=['GET', 'POST'])
@login_required
def edit_page():
    form = MultipleBatchesForm()

    batch_date = request.args.get('batch_date')
    num_batch = int(request.args.get('num_batch'))
    day_id = request.args.get('day_id')

    batches = Batches.query.filter_by(batch_date=batch_date).order_by(Batches.batch_date.asc(), Batches.schedule_id.asc()).all()
    max_shifts = fetch_max_shifts()
    if num_batch > max_shifts:
        num_batch = max_shifts

    if form.validate_on_submit():
        schedule_id_to_keep = []
        for index, batch_form in enumerate(form.batches):
            schedule_id = index+1
            batch_date = batch_date
            start_time = batch_form.start_time.data
            end_time = batch_form.end_time.data
            max_tickets = batch_form.capacity.data
            day_id = day_id

            count = update_and_add_new_batch(day_id, schedule_id, batch_date, start_time, end_time, max_tickets)
            schedule_id_to_keep.append(schedule_id)
            if count > 0:
                flash(f"Add New Date on {batch_date}", category="success")    
            else:
                flash("Failed to updated", category="warning")

        
        for batch in batches:
            curr_schedule = batch.schedule_id
            if curr_schedule not in schedule_id_to_keep:
                status = delete_batch_by_date_scheduleid(batch_date, curr_schedule)
                if status:
                    flash(f"Success delete shift-{curr_schedule} in {batch_date}", category="success")
                else:
                    flash(f"Failed delete shift-{curr_schedule} in {batch_date}", category="warning")
                    
        return redirect(url_for('boardpanel.boardpanel_page'))

    for batch in batches:
        batch_form = NewBatchForm(
            start_time = batch.start_time,
            end_time = batch.end_time,
            capacity = batch.max_tickets
        )
        form.batches.append_entry(batch_form.data)
    
    if num_batch > len(batches) and num_batch <= max_shifts:
        default_set = Default_batch.query.filter_by(default_batch_id=1).first()
        
        for num in range(len(batches), num_batch):
            cur_batch_attr_start =f"batch{num+1}_start"
            cur_batch_attr_end =f"batch{num+1}_end"

terapiketok/templates/boardpanel/addmanual.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<h2 class="h3">Add customer manually</h2>
<p class="pb-3">Choose which shift to add customer</p>
<!-- Available Batches -->
{% for batch in batches %}
            
<a href={{ url_for('boardpanel.batch_to_add_page', batch_id=batch.batch_id) }} style="display: block; text-decoration: none;">
    <div class="card mb-3" style="max-width: 540px; border-radius: 10px;">
        <div class="row g-0">
            <!-- left side -->
            <div class="col-2 bgActive text-light d-flex flex-column justify-content-center align-items-center" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
                <h3 class="card-title" style="font-size: 36px; margin: 0;">{{ batch.day_id }}</h3>
                <small>{{ batch.workingdays.day_name_ina }}</small>
            </div>
            <!-- middle side -->
            <div class="col-9 text-dark">
                <div class="card-body" style="padding: 0.5rem 1rem;">
                <h6 class="card-title" style="font-weight: 400; line-height: 0.9; margin: 0;"> Shift-{{ batch.schedule_id }}</h6>
                <p class="card-text" style="font-size: 18px; line-height: 1; margin: 5px 0">Jam: {{ batch.start_time.strftime('%H:%M') }} - {{ batch.end_time.strftime('%H:%M') }}</p>
                <p class="card-text" style="line-height: 0.9; "><small class="text-muted">{{ batch.batch_date.strftime('%d-%b-%Y') }} - already booked: {{ batch.current_tickets }}/{{ batch.max_tickets }}</small></p>
                </div>
            </div>
            <!-- right side -->
            <div class="col-1 d-flex justify-content-center align-items-center bgCustom{{batch.status}} text-light" style="border-top-right-radius: 10px; border-bottom-right-radius: 10px;">
                <span style="transform: rotate(-90deg);">{{ batch.status }}</span>
            </div>
        </div>
    </div>
</a>
{% endfor %}
{% endblock %}

terapiketok/templates/boardpanel/adminlogin.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="row p-2">
                {{ form.username(class="form-control mb-1") }}
                {{ form.password(class="form-control mb-1") }}
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
        <a href="{{url_for('boardpanel.adminregister_page')}}">Don't have an account? Sign Up</a><br>
    </div>
</main>
{% endblock %}

terapiketok/templates/boardpanel/adminregister.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="row p-2">
                {{ form.username(class="form-control mb-1") }}
                {{ form.password(class="form-control mb-1") }}
                {{ form.confirm_password(class="form-control mb-1") }}
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
        <a href="{{url_for('boardpanel.adminlogin_page')}}">Already have an account? Login</a><br>
    </div>
</main>
{% endblock %}

terapiketok/templates/boardpanel/batch_to_add.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<div class="d-flex flex-column">
    <div>{{ batch.workingdays.day_name_ina }}, {{ batch.batch_date.strftime('%d-%b-%Y') }}</div>
        <div>Shitf-{{ batch.schedule_id }}, jam {{ batch.start_time.strftime('%H:%M') }}-{{ batch.end_time.strftime('%H:%M') }}</div>
        <div>Booked: {{ batch.current_tickets }} / {{ batch.max_tickets }}</div>
        <div class="pb-3">Status: {{ batch.status }}</div>
        <div class="card p-2 mb-5">
            Add customer:
            <form method="POST" onSubmit="return confirm('Are you sure to add this customer?')">
                {{ form.hidden_tag() }}
                <div style="max-width: 250px;">
                    <div class="d-flex justify-content-between mb-2">
                        {{ form.username.label() }}{{ form.username() }}
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        {{ form.phone.label() }}{{ form.phone() }}
                    </div>
                    {{ form.submit(class="form-control btn btn-success btn-sm") }}
                </div>
            </form>
        </div>
</div>
{% endblock %}

terapiketok/templates/boardpanel/batches.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <h1>Existing batches</h1>
</main>

{% endblock %}

terapiketok/templates/boardpanel/boardpanel.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <div class="row">
            
            <div class="col p-0">
                <a href={{ url_for('boardpanel.newdate_page') }} style="text-decoration: none;">
                    <div class="card m-1 p-3 text-center" style="border-radius: 10px;">
                        New Date
                    </div>
                </a>
                <a href={{ url_for('boardpanel.default_page') }} style="text-decoration: none;">
                    <div class="card m-1 p-3 text-center" style="border-radius: 10px;">
                        Default
                    </div>
                </a>
            </div>

            <div class="col p-0">
                <a href={{ url_for('boardpanel.addmanual_page') }} style="text-decoration: none;">
                    <div class="card m-1 p-3 text-center" style="border-radius: 10px;">
                        Add manual
                    </div>
                </a>
                <a href={{ url_for('boardpanel.editoption_page', action="edit") }} style="text-decoration: none;">
                    <div class="card m-1 p-3 text-center" style="border-radius: 10px;">
                        Edit / Delete
                    </div>
                </a>
            </div>

        </div>

        <!-- Available Batches -->
         {% for batch in batches %}
            
            <a href={{ url_for('boardpanel.batchdetail_page', batch_id=batch.batch_id) }} style="display: block; text-decoration: none;">
                <div class="card mb-3" style="max-width: 540px; border-radius: 10px;">
                    <div class="row g-0">
                        <!-- left side -->
                        <div class="col-2 bgActive text-light d-flex flex-column justify-content-center align-items-center" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
                            <h3 class="card-title" style="font-size: 36px; margin: 0;">{{ batch.day_id }}</h3>
                            <small>{{ batch.workingdays.day_name_ina }}</small>
                        </div>
                        <!-- middle side -->
                        <div class="col-9 text-dark">
                            <div class="card-body" style="padding: 0.5rem 1rem;">
                            <h6 class="card-title" style="font-weight: 400; line-height: 0.9; margin: 0;"> Shift-{{ batch.schedule_id }}</h6>
                            <p class="card-text" style="font-size: 18px; line-height: 1; margin: 5px 0">Jam: {{ batch.start_time.strftime('%H:%M') }} - {{ batch.end_time.strftime('%H:%M') }}</p>
                            <p class="card-text" style="line-height: 0.9; "><small class="text-muted">{{ batch.batch_date.strftime('%d-%b-%Y') }} - already booked: {{ batch.current_tickets }}/{{ batch.max_tickets }}</small></p>
                            </div>
                        </div>
                        <!-- right side -->
                        <div class="col-1 d-flex justify-content-center align-items-center bgCustom{{batch.status}} text-light" style="border-top-right-radius: 10px; border-bottom-right-radius: 10px;">
                            <span style="transform: rotate(-90deg);">{{ batch.status }}</span>
                        </div>
                    </div>
                </div>
            </a>
         {% endfor %}

        <a href="{{url_for('boardpanel.logout_page')}}">LOGOUT</a><br>
    </div>
</main>
{% endblock %}

terapiketok/templates/boardpanel/default.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div>
        <a href={{ url_for('boardpanel.defaultmessage_page') }} style="text-decoration: none;">
            <div class="card p-3 m-3 text-center" style="border-radius: 10px;">
                Opening Massage
            </div>
        </a>
    </div>
    <div>
        <a href={{ url_for('boardpanel.defaultbatch_page') }} style="text-decoration: none;">
            <div class="card p-3 m-3 text-center" style="border-radius: 10px;">
                Batch setting
            </div>
        </a>
    </div>
</main>
{% endblock %}

terapiketok/templates/boardpanel/defaultbatch.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <form method="POST" style="font-size: smaller;">
            {{ form.hidden_tag() }}
            <div class="row mb-3">
                <div class="col">
                    Capacity / batch
                    {{ form.capacity(class="form-control", value=default_set.capacity, style="font-size: small") }}
                </div>
                <div class="col">
                    Booking / HP
                    {{ form.booking_limit(class="form-control", value=default_set.booking_limit, style="font-size: small") }}
                </div>
            </div>
            <div class="d-flex mb-3">
                <div class="flex-fill align-self-center">
                    Jumlah Shift/Batch
                </div>
                <div class="flex-fill">
                    {{ form.number_of_batches(class="form-control", value=default_set.number_of_batches, style="font-size: small") }}
                </div>
            </div>
            gunakan format seperti ini: 08:00
            <div class="d-flex flex-wrap mb-3">
                <div class="col-4 adjustCol mb-3 p-1">
                    Shift 1
                    {{ form.batch1_start(class="form-control", value=default_set.batch1_start, style="font-size: small")}}
                    {{ form.batch1_end(class="form-control", value=default_set.batch1_end, style="font-size: small")}}
                </div>
                <div class="col-4 adjustCol p-1">
                    Shift 2
                    {{ form.batch2_start(class="form-control", value=default_set.batch2_start, style="font-size: small")}}
                    {{ form.batch2_end(class="form-control", value=default_set.batch2_end, style="font-size: small")}}
                </div>
                <div class="col-4 adjustCol p-1">
                    Shift 3
                    {{ form.batch3_start(class="form-control", value=default_set.batch3_start, style="font-size: small")}}
                    {{ form.batch3_end(class="form-control", value=default_set.batch3_end, style="font-size: small")}}
                </div>
                <div class="col-4 adjustCol p-1">
                    Shift 4
                    {{ form.batch4_start(class="form-control", value=default_set.batch4_start, style="font-size: small")}}
                    {{ form.batch4_end(class="form-control", value=default_set.batch4_end, style="font-size: small")}}
                </div>
                <div class="col-4 adjustCol p-1">
                    Shift 5
                    {{ form.batch5_start(class="form-control", value=default_set.batch5_start, style="font-size: small")}}
                    {{ form.batch5_end(class="form-control", value=default_set.batch5_end, style="font-size: small")}}
                </div>
            </div>
            
            {{ form.submit(class="btn btn-success form-control p-2") }}
        </form>
    </div>
</main>

{% endblock %}

terapiketok/templates/boardpanel/delete.html
{% extends 'baseboardpanel.html' %}

{% block content %}
    <h2 class="fs-5">Delete</h2>
    <div class="d-flex flex-column">
        <div class="row"><div class="col-3">Tanggal</div>: {{ batch_date.strftime('%d-%b-%Y') }}</div>
        <div class="row"><div class="col-3">Hari</div>: {{ day_ina_name }}</div>
        <div class="row"><div class="col-3">Jumlah Shift</div>: {{ num_batch }}</div>
    </div>
    <div class="d-flex mt-3">
        <a href="{{ url_for('boardpanel.delete_page', batch_date=batch_date.strftime('%Y-%m-%d'), num_batch=num_batch, day_ina_name=day_ina_name, default_check=True) }}">
            <div class="form-check">
                
                <label class="form-check-label" for="flexCheckDefault">
                  Check All
                </label>
              </div>
        </a>
    </div>
    <form method="POST">
        {{ form.hidden_tag() }}
        <table class="table">
            <thead>
                <tr>
                  <th scope="col">del</th>
                  <th scope="col">shift</th>
                  <th scope="col">jadwal</th>
                  <th scope="col">tickets</th>
                  <th scope="col">status</th>
                </tr>
              </thead>
              <tbody>

                  {% for index, batch_form in enumerate(form.batches) %}
                  <tr>
                    {{ batch_form.hidden_tag() }}
                    <th scope="row">{{ batch_form.batch_checkboxes() }}</th>
                    <td>{{ options[index][1] }}</td>
                    <td>{{ options[index][2].strftime('%H:%M') }}-{{ options[index][3].strftime('%H:%M') }}</td>
                    <td>{{ options[index][4] }}/{{ options[index][5] }}</td>
                    <td>{{ options[index][6] }}</td>
                    <td>{{ batch_form.fixed_value(value=options[index][0], class="form-control visually-hidden") }}</td>
                  </tr>
                      
                  {% endfor %}

              </tbody>

        </table>
        {{ form.submit(class="btn btn-success p-2") }}
        
    </form>
{% endblock %}

terapiketok/templates/boardpanel/edit.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <h2 class="fs-5">Edit</h2>
        <div class="d-flex flex-column">
            <div class="row">
                <div class="col-3">
                    Tanggal
                </div>
                : {{ new_date }}
            </div>
            <div class="row">
                <div class="col-3">Jumlah Shift</div>
                : {{ num_batch }}
            </div>
            <div class="row mb-3">
                <div class="col-3">
                    <div class="d-flex justify-content-center align-items-center" style="background-color: #198754; color: white;">
                        <a href="{{ url_for('boardpanel.edit_page', batch_date=new_date, num_batch=num_batch-1, day_id=day_id) }}" style="display: block; text-decoration: none;">
                            <div class="fs-4 px-2" style="color: white;">
                            -
                            </div>
                        </a>
                        <div class="fs-5">
                            shift
                        </div>
                        <a href="{{ url_for('boardpanel.edit_page', batch_date=new_date, num_batch=num_batch+1, day_id=day_id) }}" style="display: block; text-decoration: none;">
                            <div class="fs-4 px-2" style="color: white;">
                            +
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <form method="POST" style="font-size: smaller;">
            {{ form.hidden_tag() }}
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">shift</th>
                    <th scope="col">Start</th>
                    <th scope="col">End</th>
                    <th scope="col">Capacity</th>
                  </tr>
                </thead>
                <tbody>
                    {% for index, batch_form in enumerate(form.batches) %}
                    <tr>
                        {{ batch_form.hidden_tag() }}
                        <th scope="row">shift{{ index + 1 }}</th>
                        <td>{{ batch_form.start_time() }}</td>
                        <td>{{ batch_form.end_time() }}</td>
                        <td>{{ batch_form.capacity() }}</td>
                    </tr>
                    {% endfor %}
                  
                </tbody>
              </table>

            {{ form.submit(class="btn btn-success form-control p-2") }}
        </form>
    </div>
</main>

{% endblock %}

terapiketok/templates/boardpanel/editoption.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<div class="d-flex align-items-center">
    <h2 class="h3 p-2">{{ head_text.upper() }}</h2>
    <a href="{{ url_for('boardpanel.editoption_page', action=next_action) }}" class="small"> {{ next_action }}</a><br>

</div>
    <div class="d-flex flex-column mb-3">
        {% for date_info in dates %}
            {% if next_action == 'edit' %}
                <a href="{{ url_for('boardpanel.delete_page', batch_date=date_info[0], num_batch=date_info[3], day_ina_name=date_info[1], default_check=False) }}" style="display: block; text-decoration: none;">
                    <div class="card p-2 text-center mb-2" style="max-width: 200px; border-radius: 10px;">
                        {{ date_info[1] }} {{ date_info[0].strftime('%d-%b-%Y') }}
                    </div>
                </a>
                {% elif next_action == 'delete' %}
                <a href="{{ url_for('boardpanel.edit_page', batch_date=date_info[0], num_batch=date_info[3], day_id=date_info[2]) }}" style="display: block; text-decoration: none;">
                    <div class="card p-2 text-center mb-2" style="max-width: 200px; border-radius: 10px;">
                        {{ date_info[1] }} {{ date_info[0].strftime('%d-%b-%Y') }}
                    </div>
                </a>
            {% else %}
                <h6>Something wrong, to match action.Should be 'edit' or 'delete'</h6>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

terapiketok/templates/boardpanel/newbatch.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <h2 class="fs-5">Open New Date</h2>
        <div class="d-flex flex-column">
            <div class="row">
                <div class="col-3">
                    Tanggal
                </div>
                : {{ new_date }}
            </div>
            <div class="row">
                <div class="col-3">Jumlah Shift</div>
                : {{ batches }}
            </div>
        </div>
        <form method="POST" style="font-size: smaller;">
            {{ form.hidden_tag() }}
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">shift</th>
                    <th scope="col">Start</th>
                    <th scope="col">End</th>
                    <th scope="col">Capacity</th>
                  </tr>
                </thead>
                <tbody>
                    {% for index, batch_form in enumerate(form.batches) %}
                    <tr>
                        {{ batch_form.hidden_tag() }}
                        <th scope="row">shift{{ index + 1 }}</th>
                        <td>{{ batch_form.start_time() }}</td>
                        <td>{{ batch_form.end_time() }}</td>
                        <td>{{ batch_form.capacity() }}</td>
                    </tr>
                    {% endfor %}
                  
                </tbody>
              </table>

            {{ form.submit(class="btn btn-success form-control p-2") }}
        </form>
    </div>
</main>

{% endblock %}

terapiketok/templates/boardpanel/newdate.html
{% extends 'baseboardpanel.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="p-3">
        <form method="POST" style="font-size: smaller;">
            {{ form.hidden_tag() }}
            <div class="d-flex align-items-center">
                <div class="mr-3">
                    {{ form.batches.label() }}
                </div>
                <div class="m-3">
                    {{ form.batches(value=batches, style="font-size: small")}}
                </div>
            </div>
            <div class="mb-3">
                {{ form.batch_date.label() }}
                {{ form.batch_date(class="form-control", style="font-size: small", valus=new_date)}}
            </div>

            {{ form.submit(class="btn btn-success form-control p-2") }}
        </form>
    </div>
</main>

{% endblock %}