terapiketok/routes/home.py
import datetime, uuid
from flask import Blueprint, render_template_string, render_template, request, redirect, url_for, session, flash
from ..services.database import fetch_available_batch, create_booking, fetct_queue_number
from ..services.data_processing import authenticate_user, get_queue_number
from ..forms import LoginForm, ConfirmationForm, CloseTicketButton
from ..models import Batches, Booking_tickets
from terapiketok import db

home_bp = Blueprint('home', __name__, template_folder="../templates/home")

@home_bp.route('/', methods=['GET', 'POST'])
@home_bp.route('/home', methods=['GET', 'POST'])
def home_page():
    text_header = "Harap masukkan nama dan nomor HP"
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        phone = form.phone.data

        if authenticate_user(username, phone):
            # Redirect to the home page after successful login
            session["username"] = username
            session["phone"] = phone
            return redirect(url_for('.register_page'))
    return render_template('home.html', form=form, text_header=text_header)

@home_bp.route('/register', methods=['GET', 'POST'])
def register_page():
    username = session.get("username")
    phone = session.get("phone")

    if authenticate_user(username, phone) == False:
        return redirect(url_for('.home_page'))

    text_header = f"Selamat datang, {username}"
    today = datetime.date.today()
    tomorrow = today + datetime.timedelta(days=1)
    
    batches = fetch_available_batch(tomorrow)
    clean_batches = []
    for batch in batches:
        batch_date = batch[0].strftime('%d-%m-%Y')
        batch_day = batch[1]
        schedule_id = batch[2]
        schedule_name = batch[3]
        start_hour = batch[4].strftime('%H:%M')
        end_hour = batch[5].strftime('%H:%M')
        status = batch[8]
        batch_id = batch[9]

        classes = {
            "OPEN": ("bgActive", "text-dark", "success"),
            "CLOSED": ("bgNonActive", "white-transparent", "danger")
        }
        left_side_class, middle_side_class, right_side_class = classes.get(status, ("bgNonActive", "white-transparent", "danger"))

        clean_batches.append(
            (batch_date, batch_day, schedule_id, schedule_name, start_hour, end_hour, status,
              left_side_class, middle_side_class, right_side_class, batch_id)
        )

    return render_template('register.html', batches=clean_batches, text_header=text_header)


@home_bp.route('/confirmation/<int:batch_id>', methods=['GET', 'POST'])
def confirmation_page(batch_id):
    batch = Batches.query.filter_by(batch_id=batch_id).first()

    # Check if the batch status is "OPEN"
    if batch.status != "OPEN":
        flash("Batch is not open for booking.", "warning")
        return redirect(url_for('.register_page'))

    username = session.get("username")
    phone = session.get("phone")
    
    batch = Batches.query.get(batch_id)
    
    if batch is None:
         return redirect(url_for('.register_page'))
    
    form = ConfirmationForm()

    if form.validate_on_submit():
        appointment_date = batch.batch_date
        
        # Version 4 (randomly generated)
        ticket_uid = uuid.uuid4()
        status, message = create_booking(batch_id, username, phone, appointment_date, ticket_uid)
        if status:
            session["ticket"] = ticket_uid
            flash(message, category="success")
            return redirect(url_for('.ticket_page'))
        else:
            flash(message, category="danger")
            return redirect(url_for('.register_page'))
    
    return render_template('confirmation.html', batch=batch, username=username, phone=phone, form=form)

@home_bp.route('/ticket', methods=['GET', 'POST'])
def ticket_page():
    form = CloseTicketButton()
    if form.validate_on_submit():
        return redirect(url_for('.register_page'))
    
    ticket_uid = session.get("ticket")
    if not ticket_uid:
        flash(f"Tidak dapat Tiket. Mohon maaf", category="danger")
        return redirect(url_for(".register_page"))
    
    ticket = Booking_tickets.query.get(ticket_uid)
    # Check if the ticket has been used
    if ticket.used:
        flash("This ticket has already been used.", "warning")
        return redirect(url_for('.register_page'))
    
    # Mark the ticket as used
    ticket.used = True
    db.session.commit()
    session.pop('ticket', None) # erase session ticket

    list_queue = fetct_queue_number(ticket.batch_id)
    queue_number = get_queue_number(list_queue, ticket_uid)
    if queue_number == -1:
        queue_number = "XX"
    
    return render_template('ticket.html', ticket=ticket, queue_number=queue_number, form=form)



terapiketok/templates/home/confirmation.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light d-flex justify-content-center align-items-center p-2" style="min-height: 100vh;">
    <div class="card p-2" style="min-width: 200px;">
        <h2 style="font-size: 1.2rem;">Check apakah sudah benar</h2>
        <ul class="list-group list-group-flush" style="font-size: 0.9rem;">
            <li class="list-group-item">Nama: <b>{{ username }}</b></li>
            <li class="list-group-item">No. HP: <b>{{ phone }}</b></li>
            <li class="list-group-item">Hari: <b>{{ batch.workingdays.day_name_ina }}</b></li>
            <li class="list-group-item">Tgl Booking: <b>{{ batch.batch_date.strftime('%d-%B-%Y')}}</b></li>
            <li class="list-group-item">Sesi: <b>{{ batch.schedule_id}}</b></li>
            <li class="list-group-item mb-3">Jam: <b>{{ batch.start_time.strftime('%H:%M') }} - {{ batch.end_time.strftime('%H:%M') }}</b></li>
        </ul>
        <div class="d-flex gap-1 justify-content-center">
            <a href="{{ url_for('home.register_page') }}"><button class="btn btn-danger p-2" style="min-width: 30%;">NO</button></a>
            <form method="POST" class="flex-fill">
                {{ form.hidden_tag() }}
                {{ form.submit(class="btn btn-success form-control p-2") }}
            </form>
        </div>
    </div>

</main>
{% endblock %}

terapiketok/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="heroSection">
        <header class="text-center">
            <h1>TERAPI KETOK</h1>
            <h2>Mr. KEVIN</h2>
        </header>
        <address class="text-center">
            Garden Hous Grand Wisata<br>
            blok BG1 no.33 Lambangjaya<br>
            Tambun Selatan<br>
            Bekasi 17510 
        </address>
    </div>
    <div class="mx-4 p-2">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label() }}
                {{ form.username(class="form-control", placeholder="Nama") }}
            </div>
    
            <div class="mb-3">
                {{ form.phone.label() }}
                {{ form.phone(class="form-control", placeholder="Nomer HP") }}
            </div>
            {{ form.submit(class="form-control btn btn-success") }}
        </form>
    </div>
</main>
{% endblock %}

terapiketok/templates/home/register.html
{% extends 'base.html' %}

{% block title %}
Registrasi
{% endblock %}

{% block content %}

<main class="container bg-light p-0" style="min-height: 100vh;">
    <div class="heroSection">
        <header class="text-center">
            <h1>TERAPI KETOK</h1>
            <h2>Mr. KEVIN</h2>
        </header>
        <address class="text-center">
            Garden Hous Grand Wisata<br>
            blok BG1 no.33 Lambangjaya<br>
            Tambun Selatan<br>
            Bekasi 17510 
        </address>
    </div>
    
    <div class="pb-3 mx-3">
        {% for batch in batches %}
            {% if batch[6].upper() == "OPEN" %}
                <a href="{{ url_for('home.confirmation_page', batch_id=batch[10]) }}" style="display: block; text-decoration: none;">
                    <div class="card mb-3" style="max-width: 540px; border-radius: 10px;">
                        <div class="row g-0">
                            <!-- left side -->
                            <div class="col-2 {{batch[7]}} text-light d-flex flex-column justify-content-center align-items-center" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
                                <small>SESI</small>
                                <h3 class="card-title" style="font-size: 36px; margin: 0;">{{ batch[2]}}</h3>
                            </div>
                            <!-- middle side -->
                            <div class="col-9 {{batch[8]}}">
                                <div class="card-body" style="padding: 0.5rem 1rem;">
                                <h6 class="card-title" style="font-weight: 400; line-height: 0.9; margin: 0;">{{ batch[3]}}</h6>
                                <p class="card-text" style="font-size: 18px; line-height: 1; margin: 5px 0">Jam: {{ batch[4]}} - {{ batch[5]}}</p>
                                <p class="card-text" style="line-height: 0.9; "><small class="text-muted">{{ batch[1]}} - {{ batch[0]}}</small></p>
                                </div>
                            </div>
                            <!-- right side -->
                            <div class="col-1 d-flex justify-content-center align-items-center bg-{{batch[9]}} text-light" style="border-top-right-radius: 10px; border-bottom-right-radius: 10px;">
                                <span style="transform: rotate(-90deg);">{{ batch[6] }}</span>
                            </div>
                        </div>
                    </div>     
                </a>
            {% else %}
            <div class="card mb-3" style="max-width: 540px; border-radius: 10px;">
                <div class="row g-0">
                    <!-- left side -->
                    <div class="col-2 {{batch[7]}} text-light d-flex flex-column justify-content-center align-items-center" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
                        <small>SESI</small>
                        <h3 class="card-title" style="font-size: 36px; margin: 0;">{{ batch[2]}}</h3>
                    </div>
                    <!-- middle side -->
                    <div class="col-9 {{batch[8]}}">
                        <div class="card-body" style="padding: 0.5rem 1rem;">
                        <h6 class="card-title" style="font-weight: 400; line-height: 0.9; margin: 0;">{{ batch[3]}}</h6>
                        <p class="card-text" style="font-size: 18px; line-height: 1; margin: 5px 0">Jam: {{ batch[4]}} - {{ batch[5]}}</p>
                        <p class="card-text" style="line-height: 0.9; "><small class="text-muted">{{ batch[1]}} - {{ batch[0]}}</small></p>
                        </div>
                    </div>
                    <!-- right side -->
                    <div class="col-1 d-flex justify-content-center align-items-center bg-{{batch[9]}} text-light" style="border-top-right-radius: 10px; border-bottom-right-radius: 10px;">
                        <span style="transform: rotate(-90deg);">{{ batch[6] }}</span>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</main>

{% endblock %}

terapiketok/templates/home/ticket.html
{% extends 'base.html' %}

{% block content %}
<main class="container bg-light d-flex justify-content-center align-items-center p-2" style="min-height: 100vh;">
    <div class="card shadow p-3 mb-5 bg-body rounded" style="min-width: 200px;">
        <div>
            <h2 class="text-center">{{ ticket.customer_name }}</h2>
            <div  class="d-flex justify-content-between align-items-center">
                <div>No HP</div>
                <div>{{ ticket.phone }}</div>
            </div>
            <div  class="d-flex justify-content-between align-items-center">
                <div>Tanggal</div>
                <div>{{ ticket.batches.batch_date.strftime('%d-%B-%Y') }}</div>
            </div>
            <div  class="d-flex justify-content-between align-items-center">
                <div>Sesi</div>
                <div>{{ ticket.batches.schedule_id }}</div>
            </div>
            <div  class="d-flex justify-content-between align-items-center">
                <div>Jam</div>
                <div>{{ ticket.batches.start_time.strftime('%H:%M') }} - {{ ticket.batches.end_time.strftime('%H:%M') }}</div>
            </div>
            <div  class="d-flex flex-column justify-content-between align-items-center my-3">
                <div style="color: gray;">No urut</div>
                <div style="color: gray; font-size:xx-large;">{{ queue_number }}</div>
            </div>
            <div  class="d-flex flex-column justify-content-between align-items-center">
                <div style="color: gray; font-size: x-small;">Booking Code</div>
                <div style="color: gray; font-size: x-small;">{{ ticket.ticket_uid }}</div>
            </div>
            <form method="POST" class="flex-fill mt-2">
                {{ form.hidden_tag() }}
                {{ form.submit(class="btn btn-info form-control p-2") }}
            </form>
        </div>
    </div>

</main>
{% endblock %}